"""Type stubs for pylibstats package.

All distribution classes validate parameters in Python before delegating
to the native C++ extension.  Invalid parameters raise ``ValueError``.
"""

from typing import overload

import numpy as np
from numpy.typing import NDArray

from pylibstats import _core

# ---------------------------------------------------------------------------
# Common method signatures inherited by every distribution
# ---------------------------------------------------------------------------
# Each class below also exposes:
#   pdf, log_pdf, cdf   — scalar (float) and batch (NDArray) overloads
#   ppf                 — scalar only
#   fit                 — NDArray input
#   sample              — returns NDArray
#   mean, variance, std, skewness, kurtosis  — read-only float properties
#   name, support, is_discrete, num_parameters — read-only metadata
#   __repr__
# ---------------------------------------------------------------------------

class Gaussian(_core.Gaussian):
    """Gaussian (normal) distribution N(mu, sigma)."""
    def __init__(self, mu: float = 0.0, sigma: float = 1.0) -> None: ...
    @property
    def mu(self) -> float: ...
    @mu.setter
    def mu(self, value: float) -> None: ...
    @property
    def sigma(self) -> float: ...
    @sigma.setter
    def sigma(self, value: float) -> None: ...

class Exponential(_core.Exponential):
    """Exponential distribution Exp(lambda)."""
    def __init__(self, lam: float = 1.0) -> None: ...
    @property
    def lam(self) -> float: ...
    @lam.setter
    def lam(self, value: float) -> None: ...

class Uniform(_core.Uniform):
    """Continuous uniform distribution U(a, b)."""
    def __init__(self, a: float = 0.0, b: float = 1.0) -> None: ...
    @property
    def a(self) -> float: ...
    @a.setter
    def a(self, value: float) -> None: ...
    @property
    def b(self) -> float: ...
    @b.setter
    def b(self, value: float) -> None: ...

class Poisson(_core.Poisson):
    """Poisson distribution Pois(lambda)."""
    def __init__(self, lam: float = 1.0) -> None: ...
    @property
    def lam(self) -> float: ...
    @lam.setter
    def lam(self, value: float) -> None: ...

class DiscreteUniform(_core.DiscreteUniform):
    """Discrete uniform distribution over integers {a, a+1, ..., b}."""
    def __init__(self, a: int = 0, b: int = 1) -> None: ...
    @property
    def a(self) -> int: ...
    @a.setter
    def a(self, value: int) -> None: ...
    @property
    def b(self) -> int: ...
    @b.setter
    def b(self, value: int) -> None: ...

class Gamma(_core.Gamma):
    """Gamma distribution Gamma(alpha, beta)."""
    def __init__(self, alpha: float = 1.0, beta: float = 1.0) -> None: ...
    @property
    def alpha(self) -> float: ...
    @alpha.setter
    def alpha(self, value: float) -> None: ...
    @property
    def beta(self) -> float: ...
    @beta.setter
    def beta(self, value: float) -> None: ...

class Beta(_core.Beta):
    """Beta distribution Beta(alpha, beta)."""
    def __init__(self, alpha: float = 1.0, beta: float = 1.0) -> None: ...
    @property
    def alpha(self) -> float: ...
    @alpha.setter
    def alpha(self, value: float) -> None: ...
    @property
    def beta(self) -> float: ...
    @beta.setter
    def beta(self, value: float) -> None: ...

class ChiSquared(_core.ChiSquared):
    """Chi-squared distribution χ²(k)."""
    def __init__(self, k: float = 1.0) -> None: ...
    @property
    def k(self) -> float: ...
    @k.setter
    def k(self, value: float) -> None: ...

class StudentT(_core.StudentT):
    """Student's t distribution t(nu)."""
    def __init__(self, nu: float = 1.0) -> None: ...
    @property
    def nu(self) -> float: ...
    @nu.setter
    def nu(self, value: float) -> None: ...

class LogNormal(_core.LogNormal):
    """Log-normal distribution LogN(mu, sigma)."""
    def __init__(self, mu: float = 0.0, sigma: float = 1.0) -> None: ...
    @property
    def mu(self) -> float: ...
    @mu.setter
    def mu(self, value: float) -> None: ...
    @property
    def sigma(self) -> float: ...
    @sigma.setter
    def sigma(self, value: float) -> None: ...

class Pareto(_core.Pareto):
    """Pareto distribution Pareto(scale, alpha)."""
    def __init__(self, scale: float = 1.0, alpha: float = 1.0) -> None: ...
    @property
    def scale(self) -> float: ...
    @scale.setter
    def scale(self, value: float) -> None: ...
    @property
    def alpha(self) -> float: ...
    @alpha.setter
    def alpha(self, value: float) -> None: ...

class Weibull(_core.Weibull):
    """Weibull distribution W(shape, scale)."""
    def __init__(self, shape: float = 1.0, scale: float = 1.0) -> None: ...
    @property
    def shape(self) -> float: ...
    @shape.setter
    def shape(self, value: float) -> None: ...
    @property
    def scale(self) -> float: ...
    @scale.setter
    def scale(self, value: float) -> None: ...

class Rayleigh(_core.Rayleigh):
    """Rayleigh distribution R(sigma)."""
    def __init__(self, sigma: float = 1.0) -> None: ...
    @property
    def sigma(self) -> float: ...
    @sigma.setter
    def sigma(self, value: float) -> None: ...

class VonMises(_core.VonMises):
    """Von Mises distribution VM(mu, kappa)."""
    def __init__(self, mu: float = 0.0, kappa: float = 1.0) -> None: ...
    @property
    def mu(self) -> float: ...
    @mu.setter
    def mu(self, value: float) -> None: ...
    @property
    def kappa(self) -> float: ...
    @kappa.setter
    def kappa(self, value: float) -> None: ...

class Binomial(_core.Binomial):
    """Binomial distribution B(n, p)."""
    def __init__(self, n: int = 10, p: float = 0.5) -> None: ...
    @property
    def n(self) -> int: ...
    @n.setter
    def n(self, value: int) -> None: ...
    @property
    def p(self) -> float: ...
    @p.setter
    def p(self, value: float) -> None: ...

class NegativeBinomial(_core.NegativeBinomial):
    """Negative Binomial distribution NB(r, p)."""
    def __init__(self, r: float = 1.0, p: float = 0.5) -> None: ...
    @property
    def r(self) -> float: ...
    @r.setter
    def r(self, value: float) -> None: ...
    @property
    def p(self) -> float: ...
    @p.setter
    def p(self, value: float) -> None: ...

class Geometric(_core.Geometric):
    """Geometric distribution Geo(p)."""
    def __init__(self, p: float = 0.5) -> None: ...
    @property
    def p(self) -> float: ...
    @p.setter
    def p(self, value: float) -> None: ...

class Laplace(_core.Laplace):
    """Laplace distribution Laplace(mu, b)."""
    def __init__(self, mu: float = 0.0, b: float = 1.0) -> None: ...
    @property
    def mu(self) -> float: ...
    @mu.setter
    def mu(self, value: float) -> None: ...
    @property
    def b(self) -> float: ...
    @b.setter
    def b(self, value: float) -> None: ...

class Cauchy(_core.Cauchy):
    """Cauchy distribution Cauchy(x0, gamma). Mean/variance/skewness/kurtosis are NaN."""
    def __init__(self, x0: float = 0.0, gamma: float = 1.0) -> None: ...
    @property
    def x0(self) -> float: ...
    @x0.setter
    def x0(self, value: float) -> None: ...
    @property
    def gamma(self) -> float: ...
    @gamma.setter
    def gamma(self, value: float) -> None: ...

Normal = Gaussian

__all__ = [
    "Beta",
    "Binomial",
    "Cauchy",
    "ChiSquared",
    "DiscreteUniform",
    "Exponential",
    "Gamma",
    "Gaussian",
    "Geometric",
    "Laplace",
    "LogNormal",
    "NegativeBinomial",
    "Normal",
    "Pareto",
    "Poisson",
    "Rayleigh",
    "StudentT",
    "Uniform",
    "VonMises",
    "Weibull",
]
