"""Type stubs for the pylibstats._core native extension module.

Internal: users should import from ``pylibstats`` (not ``pylibstats._core``)
to get validated wrapper classes.  The public API stubs are in __init__.pyi.

Mutable distribution parameters (mu, sigma, lam, etc.) are omitted here
because the wrapper classes in __init__.py override them with validated
Python properties.
"""

from typing import overload

import numpy as np
from numpy.typing import NDArray

# ---------------------------------------------------------------------------
# Every distribution class exposes these methods and read-only properties
# (bound by bind_common_methods<> in _core.cpp).  Per-distribution
# constructors and mutable parameters are listed on each class.
# ---------------------------------------------------------------------------
#   pdf(x), log_pdf(x), cdf(x)  — scalar and NDArray overloads
#   ppf(p: float) -> float
#   fit(data: NDArray[np.float64]) -> None
#   sample(n=1, seed=None) -> NDArray[np.float64]
#   __repr__() -> str
#
#   Properties (read-only):
#     mean, variance, std, skewness, kurtosis  : float
#     name : str
#     support : tuple[float, float]
#     is_discrete : bool
#     num_parameters : int
# ---------------------------------------------------------------------------

class Gaussian:
    def __init__(self, mu: float = 0.0, sigma: float = 1.0) -> None: ...
    @overload
    def pdf(self, x: float) -> float: ...
    @overload
    def pdf(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...
    @overload
    def log_pdf(self, x: float) -> float: ...
    @overload
    def log_pdf(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...
    @overload
    def cdf(self, x: float) -> float: ...
    @overload
    def cdf(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...
    def ppf(self, p: float) -> float: ...
    def fit(self, data: NDArray[np.float64]) -> None: ...
    def sample(self, n: int = 1, seed: int | None = None) -> NDArray[np.float64]: ...
    def __repr__(self) -> str: ...
    @property
    def mean(self) -> float: ...
    @property
    def variance(self) -> float: ...
    @property
    def std(self) -> float: ...
    @property
    def skewness(self) -> float: ...
    @property
    def kurtosis(self) -> float: ...
    @property
    def name(self) -> str: ...
    @property
    def support(self) -> tuple[float, float]: ...
    @property
    def is_discrete(self) -> bool: ...
    @property
    def num_parameters(self) -> int: ...

class Exponential:
    def __init__(self, lam: float = 1.0) -> None: ...
    @overload
    def pdf(self, x: float) -> float: ...
    @overload
    def pdf(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...
    @overload
    def log_pdf(self, x: float) -> float: ...
    @overload
    def log_pdf(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...
    @overload
    def cdf(self, x: float) -> float: ...
    @overload
    def cdf(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...
    def ppf(self, p: float) -> float: ...
    def fit(self, data: NDArray[np.float64]) -> None: ...
    def sample(self, n: int = 1, seed: int | None = None) -> NDArray[np.float64]: ...
    def __repr__(self) -> str: ...
    @property
    def mean(self) -> float: ...
    @property
    def variance(self) -> float: ...
    @property
    def std(self) -> float: ...
    @property
    def skewness(self) -> float: ...
    @property
    def kurtosis(self) -> float: ...
    @property
    def name(self) -> str: ...
    @property
    def support(self) -> tuple[float, float]: ...
    @property
    def is_discrete(self) -> bool: ...
    @property
    def num_parameters(self) -> int: ...

class Uniform:
    def __init__(self, a: float = 0.0, b: float = 1.0) -> None: ...
    @overload
    def pdf(self, x: float) -> float: ...
    @overload
    def pdf(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...
    @overload
    def log_pdf(self, x: float) -> float: ...
    @overload
    def log_pdf(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...
    @overload
    def cdf(self, x: float) -> float: ...
    @overload
    def cdf(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...
    def ppf(self, p: float) -> float: ...
    def fit(self, data: NDArray[np.float64]) -> None: ...
    def sample(self, n: int = 1, seed: int | None = None) -> NDArray[np.float64]: ...
    def __repr__(self) -> str: ...
    @property
    def mean(self) -> float: ...
    @property
    def variance(self) -> float: ...
    @property
    def std(self) -> float: ...
    @property
    def skewness(self) -> float: ...
    @property
    def kurtosis(self) -> float: ...
    @property
    def name(self) -> str: ...
    @property
    def support(self) -> tuple[float, float]: ...
    @property
    def is_discrete(self) -> bool: ...
    @property
    def num_parameters(self) -> int: ...

class Poisson:
    def __init__(self, lam: float = 1.0) -> None: ...
    @overload
    def pdf(self, x: float) -> float: ...
    @overload
    def pdf(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...
    @overload
    def log_pdf(self, x: float) -> float: ...
    @overload
    def log_pdf(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...
    @overload
    def cdf(self, x: float) -> float: ...
    @overload
    def cdf(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...
    def ppf(self, p: float) -> float: ...
    def fit(self, data: NDArray[np.float64]) -> None: ...
    def sample(self, n: int = 1, seed: int | None = None) -> NDArray[np.float64]: ...
    def __repr__(self) -> str: ...
    @property
    def mean(self) -> float: ...
    @property
    def variance(self) -> float: ...
    @property
    def std(self) -> float: ...
    @property
    def skewness(self) -> float: ...
    @property
    def kurtosis(self) -> float: ...
    @property
    def name(self) -> str: ...
    @property
    def support(self) -> tuple[float, float]: ...
    @property
    def is_discrete(self) -> bool: ...
    @property
    def num_parameters(self) -> int: ...

class DiscreteUniform:
    def __init__(self, a: int = 0, b: int = 1) -> None: ...
    @overload
    def pdf(self, x: float) -> float: ...
    @overload
    def pdf(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...
    @overload
    def log_pdf(self, x: float) -> float: ...
    @overload
    def log_pdf(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...
    @overload
    def cdf(self, x: float) -> float: ...
    @overload
    def cdf(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...
    def ppf(self, p: float) -> float: ...
    def fit(self, data: NDArray[np.float64]) -> None: ...
    def sample(self, n: int = 1, seed: int | None = None) -> NDArray[np.float64]: ...
    def __repr__(self) -> str: ...
    @property
    def mean(self) -> float: ...
    @property
    def variance(self) -> float: ...
    @property
    def std(self) -> float: ...
    @property
    def skewness(self) -> float: ...
    @property
    def kurtosis(self) -> float: ...
    @property
    def name(self) -> str: ...
    @property
    def support(self) -> tuple[float, float]: ...
    @property
    def is_discrete(self) -> bool: ...
    @property
    def num_parameters(self) -> int: ...

class Gamma:
    def __init__(self, alpha: float = 1.0, beta: float = 1.0) -> None: ...
    @overload
    def pdf(self, x: float) -> float: ...
    @overload
    def pdf(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...
    @overload
    def log_pdf(self, x: float) -> float: ...
    @overload
    def log_pdf(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...
    @overload
    def cdf(self, x: float) -> float: ...
    @overload
    def cdf(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...
    def ppf(self, p: float) -> float: ...
    def fit(self, data: NDArray[np.float64]) -> None: ...
    def sample(self, n: int = 1, seed: int | None = None) -> NDArray[np.float64]: ...
    def __repr__(self) -> str: ...
    @property
    def mean(self) -> float: ...
    @property
    def variance(self) -> float: ...
    @property
    def std(self) -> float: ...
    @property
    def skewness(self) -> float: ...
    @property
    def kurtosis(self) -> float: ...
    @property
    def name(self) -> str: ...
    @property
    def support(self) -> tuple[float, float]: ...
    @property
    def is_discrete(self) -> bool: ...
    @property
    def num_parameters(self) -> int: ...

class Beta:
    def __init__(self, alpha: float = 1.0, beta: float = 1.0) -> None: ...
    @overload
    def pdf(self, x: float) -> float: ...
    @overload
    def pdf(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...
    @overload
    def log_pdf(self, x: float) -> float: ...
    @overload
    def log_pdf(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...
    @overload
    def cdf(self, x: float) -> float: ...
    @overload
    def cdf(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...
    def ppf(self, p: float) -> float: ...
    def fit(self, data: NDArray[np.float64]) -> None: ...
    def sample(self, n: int = 1, seed: int | None = None) -> NDArray[np.float64]: ...
    def __repr__(self) -> str: ...
    @property
    def mean(self) -> float: ...
    @property
    def variance(self) -> float: ...
    @property
    def std(self) -> float: ...
    @property
    def skewness(self) -> float: ...
    @property
    def kurtosis(self) -> float: ...
    @property
    def name(self) -> str: ...
    @property
    def support(self) -> tuple[float, float]: ...
    @property
    def is_discrete(self) -> bool: ...
    @property
    def num_parameters(self) -> int: ...

class ChiSquared:
    def __init__(self, k: float = 1.0) -> None: ...
    @overload
    def pdf(self, x: float) -> float: ...
    @overload
    def pdf(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...
    @overload
    def log_pdf(self, x: float) -> float: ...
    @overload
    def log_pdf(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...
    @overload
    def cdf(self, x: float) -> float: ...
    @overload
    def cdf(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...
    def ppf(self, p: float) -> float: ...
    def fit(self, data: NDArray[np.float64]) -> None: ...
    def sample(self, n: int = 1, seed: int | None = None) -> NDArray[np.float64]: ...
    def __repr__(self) -> str: ...
    @property
    def mean(self) -> float: ...
    @property
    def variance(self) -> float: ...
    @property
    def std(self) -> float: ...
    @property
    def skewness(self) -> float: ...
    @property
    def kurtosis(self) -> float: ...
    @property
    def name(self) -> str: ...
    @property
    def support(self) -> tuple[float, float]: ...
    @property
    def is_discrete(self) -> bool: ...
    @property
    def num_parameters(self) -> int: ...

class StudentT:
    def __init__(self, nu: float = 1.0) -> None: ...
    @overload
    def pdf(self, x: float) -> float: ...
    @overload
    def pdf(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...
    @overload
    def log_pdf(self, x: float) -> float: ...
    @overload
    def log_pdf(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...
    @overload
    def cdf(self, x: float) -> float: ...
    @overload
    def cdf(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...
    def ppf(self, p: float) -> float: ...
    def fit(self, data: NDArray[np.float64]) -> None: ...
    def sample(self, n: int = 1, seed: int | None = None) -> NDArray[np.float64]: ...
    def __repr__(self) -> str: ...
    @property
    def mean(self) -> float: ...
    @property
    def variance(self) -> float: ...
    @property
    def std(self) -> float: ...
    @property
    def skewness(self) -> float: ...
    @property
    def kurtosis(self) -> float: ...
    @property
    def name(self) -> str: ...
    @property
    def support(self) -> tuple[float, float]: ...
    @property
    def is_discrete(self) -> bool: ...
    @property
    def num_parameters(self) -> int: ...
