"""Type stubs for pylibstats._core native extension module."""

from typing import overload

import numpy as np
from numpy.typing import NDArray

class Gaussian:
    """Gaussian (normal) distribution N(mu, sigma)."""

    mu: float
    """Mean parameter μ."""
    sigma: float
    """Standard deviation parameter σ."""

    def __init__(self, mu: float = 0.0, sigma: float = 1.0) -> None: ...

    @overload
    def pdf(self, x: float) -> float: ...
    @overload
    def pdf(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...
    @overload
    def log_pdf(self, x: float) -> float: ...
    @overload
    def log_pdf(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...
    @overload
    def cdf(self, x: float) -> float: ...
    @overload
    def cdf(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...
    def ppf(self, p: float) -> float: ...
    def fit(self, data: NDArray[np.float64]) -> None: ...
    def sample(self, n: int = 1, seed: int | None = None) -> NDArray[np.float64]: ...
    def __repr__(self) -> str: ...

    @property
    def mean(self) -> float: ...
    @property
    def variance(self) -> float: ...
    @property
    def std(self) -> float: ...
    @property
    def skewness(self) -> float: ...
    @property
    def kurtosis(self) -> float: ...
    @property
    def name(self) -> str: ...
    @property
    def support(self) -> tuple[float, float]: ...
    @property
    def is_discrete(self) -> bool: ...
    @property
    def num_parameters(self) -> int: ...

class Exponential:
    """Exponential distribution Exp(lambda)."""

    lam: float
    """Rate parameter λ."""

    def __init__(self, lam: float = 1.0) -> None: ...

    @overload
    def pdf(self, x: float) -> float: ...
    @overload
    def pdf(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...
    @overload
    def log_pdf(self, x: float) -> float: ...
    @overload
    def log_pdf(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...
    @overload
    def cdf(self, x: float) -> float: ...
    @overload
    def cdf(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...
    def ppf(self, p: float) -> float: ...
    def fit(self, data: NDArray[np.float64]) -> None: ...
    def sample(self, n: int = 1, seed: int | None = None) -> NDArray[np.float64]: ...
    def __repr__(self) -> str: ...

    @property
    def mean(self) -> float: ...
    @property
    def variance(self) -> float: ...
    @property
    def std(self) -> float: ...
    @property
    def skewness(self) -> float: ...
    @property
    def kurtosis(self) -> float: ...
    @property
    def name(self) -> str: ...
    @property
    def support(self) -> tuple[float, float]: ...
    @property
    def is_discrete(self) -> bool: ...
    @property
    def num_parameters(self) -> int: ...

class Uniform:
    """Continuous uniform distribution U(a, b)."""

    a: float
    """Lower bound a."""
    b: float
    """Upper bound b."""

    def __init__(self, a: float = 0.0, b: float = 1.0) -> None: ...

    @overload
    def pdf(self, x: float) -> float: ...
    @overload
    def pdf(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...
    @overload
    def log_pdf(self, x: float) -> float: ...
    @overload
    def log_pdf(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...
    @overload
    def cdf(self, x: float) -> float: ...
    @overload
    def cdf(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...
    def ppf(self, p: float) -> float: ...
    def fit(self, data: NDArray[np.float64]) -> None: ...
    def sample(self, n: int = 1, seed: int | None = None) -> NDArray[np.float64]: ...
    def __repr__(self) -> str: ...

    @property
    def mean(self) -> float: ...
    @property
    def variance(self) -> float: ...
    @property
    def std(self) -> float: ...
    @property
    def skewness(self) -> float: ...
    @property
    def kurtosis(self) -> float: ...
    @property
    def name(self) -> str: ...
    @property
    def support(self) -> tuple[float, float]: ...
    @property
    def is_discrete(self) -> bool: ...
    @property
    def num_parameters(self) -> int: ...

class Poisson:
    """Poisson distribution Pois(lambda)."""

    lam: float
    """Rate parameter λ."""

    def __init__(self, lam: float = 1.0) -> None: ...

    @overload
    def pdf(self, x: float) -> float: ...
    @overload
    def pdf(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...
    @overload
    def log_pdf(self, x: float) -> float: ...
    @overload
    def log_pdf(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...
    @overload
    def cdf(self, x: float) -> float: ...
    @overload
    def cdf(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...
    def ppf(self, p: float) -> float: ...
    def fit(self, data: NDArray[np.float64]) -> None: ...
    def sample(self, n: int = 1, seed: int | None = None) -> NDArray[np.float64]: ...
    def __repr__(self) -> str: ...

    @property
    def mean(self) -> float: ...
    @property
    def variance(self) -> float: ...
    @property
    def std(self) -> float: ...
    @property
    def skewness(self) -> float: ...
    @property
    def kurtosis(self) -> float: ...
    @property
    def name(self) -> str: ...
    @property
    def support(self) -> tuple[float, float]: ...
    @property
    def is_discrete(self) -> bool: ...
    @property
    def num_parameters(self) -> int: ...

class DiscreteUniform:
    """Discrete uniform distribution over integers {a, a+1, ..., b}."""

    a: int
    """Lower bound a (integer)."""
    b: int
    """Upper bound b (integer)."""

    def __init__(self, a: int = 0, b: int = 1) -> None: ...

    @overload
    def pdf(self, x: float) -> float: ...
    @overload
    def pdf(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...
    @overload
    def log_pdf(self, x: float) -> float: ...
    @overload
    def log_pdf(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...
    @overload
    def cdf(self, x: float) -> float: ...
    @overload
    def cdf(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...
    def ppf(self, p: float) -> float: ...
    def fit(self, data: NDArray[np.float64]) -> None: ...
    def sample(self, n: int = 1, seed: int | None = None) -> NDArray[np.float64]: ...
    def __repr__(self) -> str: ...

    @property
    def mean(self) -> float: ...
    @property
    def variance(self) -> float: ...
    @property
    def std(self) -> float: ...
    @property
    def skewness(self) -> float: ...
    @property
    def kurtosis(self) -> float: ...
    @property
    def name(self) -> str: ...
    @property
    def support(self) -> tuple[float, float]: ...
    @property
    def is_discrete(self) -> bool: ...
    @property
    def num_parameters(self) -> int: ...

class Gamma:
    """Gamma distribution Gamma(alpha, beta)."""

    alpha: float
    """Shape parameter α."""
    beta: float
    """Rate parameter β."""

    def __init__(self, alpha: float = 1.0, beta: float = 1.0) -> None: ...

    @overload
    def pdf(self, x: float) -> float: ...
    @overload
    def pdf(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...
    @overload
    def log_pdf(self, x: float) -> float: ...
    @overload
    def log_pdf(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...
    @overload
    def cdf(self, x: float) -> float: ...
    @overload
    def cdf(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...
    def ppf(self, p: float) -> float: ...
    def fit(self, data: NDArray[np.float64]) -> None: ...
    def sample(self, n: int = 1, seed: int | None = None) -> NDArray[np.float64]: ...
    def __repr__(self) -> str: ...

    @property
    def mean(self) -> float: ...
    @property
    def variance(self) -> float: ...
    @property
    def std(self) -> float: ...
    @property
    def skewness(self) -> float: ...
    @property
    def kurtosis(self) -> float: ...
    @property
    def name(self) -> str: ...
    @property
    def support(self) -> tuple[float, float]: ...
    @property
    def is_discrete(self) -> bool: ...
    @property
    def num_parameters(self) -> int: ...

class Beta:
    """Beta distribution Beta(alpha, beta)."""

    alpha: float
    """Shape parameter α."""
    beta: float
    """Shape parameter β."""

    def __init__(self, alpha: float = 1.0, beta: float = 1.0) -> None: ...

    @overload
    def pdf(self, x: float) -> float: ...
    @overload
    def pdf(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...
    @overload
    def log_pdf(self, x: float) -> float: ...
    @overload
    def log_pdf(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...
    @overload
    def cdf(self, x: float) -> float: ...
    @overload
    def cdf(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...
    def ppf(self, p: float) -> float: ...
    def fit(self, data: NDArray[np.float64]) -> None: ...
    def sample(self, n: int = 1, seed: int | None = None) -> NDArray[np.float64]: ...
    def __repr__(self) -> str: ...

    @property
    def mean(self) -> float: ...
    @property
    def variance(self) -> float: ...
    @property
    def std(self) -> float: ...
    @property
    def skewness(self) -> float: ...
    @property
    def kurtosis(self) -> float: ...
    @property
    def name(self) -> str: ...
    @property
    def support(self) -> tuple[float, float]: ...
    @property
    def is_discrete(self) -> bool: ...
    @property
    def num_parameters(self) -> int: ...

class ChiSquared:
    """Chi-squared distribution χ²(k)."""

    k: float
    """Degrees of freedom k."""

    def __init__(self, k: float = 1.0) -> None: ...

    @overload
    def pdf(self, x: float) -> float: ...
    @overload
    def pdf(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...
    @overload
    def log_pdf(self, x: float) -> float: ...
    @overload
    def log_pdf(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...
    @overload
    def cdf(self, x: float) -> float: ...
    @overload
    def cdf(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...
    def ppf(self, p: float) -> float: ...
    def fit(self, data: NDArray[np.float64]) -> None: ...
    def sample(self, n: int = 1, seed: int | None = None) -> NDArray[np.float64]: ...
    def __repr__(self) -> str: ...

    @property
    def mean(self) -> float: ...
    @property
    def variance(self) -> float: ...
    @property
    def std(self) -> float: ...
    @property
    def skewness(self) -> float: ...
    @property
    def kurtosis(self) -> float: ...
    @property
    def name(self) -> str: ...
    @property
    def support(self) -> tuple[float, float]: ...
    @property
    def is_discrete(self) -> bool: ...
    @property
    def num_parameters(self) -> int: ...

class StudentT:
    """Student's t distribution t(nu)."""

    nu: float
    """Degrees of freedom ν."""

    def __init__(self, nu: float = 1.0) -> None: ...

    @overload
    def pdf(self, x: float) -> float: ...
    @overload
    def pdf(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...
    @overload
    def log_pdf(self, x: float) -> float: ...
    @overload
    def log_pdf(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...
    @overload
    def cdf(self, x: float) -> float: ...
    @overload
    def cdf(self, x: NDArray[np.float64]) -> NDArray[np.float64]: ...
    def ppf(self, p: float) -> float: ...
    def fit(self, data: NDArray[np.float64]) -> None: ...
    def sample(self, n: int = 1, seed: int | None = None) -> NDArray[np.float64]: ...
    def __repr__(self) -> str: ...

    @property
    def mean(self) -> float: ...
    @property
    def variance(self) -> float: ...
    @property
    def std(self) -> float: ...
    @property
    def skewness(self) -> float: ...
    @property
    def kurtosis(self) -> float: ...
    @property
    def name(self) -> str: ...
    @property
    def support(self) -> tuple[float, float]: ...
    @property
    def is_discrete(self) -> bool: ...
    @property
    def num_parameters(self) -> int: ...
